name       : suru-plus-icon-theme
version    : '25'
release    : 2
source     :
    - https://github.com/gusbemacbe/suru-plus/archive/v25.tar.gz : cca791db28e9d3e7de7c73b56188150eced076874dd25f7248e04d47328ebc1f
license    : |
    - GPL-3.0-or-later
    - CC-BY-SA-3.0
    - MIT
component  : desktop.theme
summary    : Suru++ 20 icon theme
description: |
    A cyberpunk, elegant, futuristic and modern third-party icons theme
install    : |
    %make install PREFIX=$installdir/usr
