name       : suru-plus-icon-theme
version    : '30.0'
release    : 4
source     :
    - https://github.com/gusbemacbe/suru-plus/archive/v30.0.tar.gz : f99bc2913ec90573cba284a830e2ac3c4a6bb9f47814b982cffabd7722ce61e5
homepage   : https://github.com/gusbemacbe/suru-plus
license    : |
    - CC-BY-SA-3.0
    - GPL-3.0-or-later
    - MIT
component  : desktop.theme
summary    : Suru++ 20 icon theme
description: |
    A cyberpunk, elegant, futuristic and modern third-party icons theme
install    : |
    %make install PREFIX=$installdir/usr
